name: EAS Update
on: push

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eas-update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn

      - uses: 8BitJonny/gh-get-current-pr@1.3.0
        id: PR
        name: Check if we're in a PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          filterOutClosed: true

      - name: Find yarn cache
        id: yarn-cache-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: expo/expo-github-action@v7
        with:
          eas-version: latest
          eas-cache: true
          expo-cache: true
          expo-version: 4.x
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish update
        run: eas update --auto
